#!/usr/bin/env bash

SINK="@DEFAULT_SINK@"

get_volume() {
    pactl get-sink-volume $SINK | awk -F'/' '{print $2}' | tr -d ' %'
}

set_volume() {
    pactl set-sink-volume $SINK "$1%"
}

toggle_mute() {
    pactl set-sink-mute $SINK toggle
}

get_mute() {
    pactl get-sink-mute $SINK | awk '{print $2}'
}

case "$1" in
    get)
        get_volume
        ;;
    set)
        set_volume "$2"
        ;;
    mute)
        toggle_mute
        ;;
    mute-status)
        get_mute
        ;;
esac
